CREATE TABLE IF NOT EXISTS tracks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  artist TEXT,
  album TEXT,
  file_path TEXT NOT NULL UNIQUE,
  duration INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
