ALTER TABLE tracks ADD COLUMN bitrate INTEGER;
ALTER TABLE tracks ADD COLUMN sample_rate INTEGER;
ALTER TABLE tracks ADD COLUMN bit_depth INTEGER;
ALTER TABLE tracks ADD COLUMN codec TEXT;
ALTER TABLE tracks ADD COLUMN container TEXT;
ALTER TABLE tracks ADD COLUMN channels INTEGER;
ALTER TABLE tracks ADD COLUMN file_size INTEGER;
